import {Inter} from 'next/font/google'
import './globals.css'
import Provider from './provider'
import { ClerkProvider } from '@clerk/nextjs'
import NavbarComponent from "../components/NavbarComponent";
import Footer from "../components/Footer";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'TimeTable Gen',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <Provider>
                        <div id="__next">
                        <NavbarComponent/>
                            {children}
                        <Footer />
                        </div>
                    </Provider>
                </body>
            </html>
        </ClerkProvider>
    )
}
